### ISSUE TITLE
rebase on original fire mod

### ISSUE THREAD

**Issue by HybridDog** [tenplus1/fire#2]
There's the history of the fire mod without the other mods:
https://github.com/HybridDog/subtree_tests/commits/fire

your fire mod could be rebased from the commit after "Move all common mods back to minetest_game" if you need the history

If new commits appear at the default fire mod, you can use git subtree to get them out of minetest_game and then you can easily put them into your repository

**Comment by tenplus1** [comment]
Thanks for info but it's fine, Fire Redo is only being used in Xanadu for now and will keep up to date manually if needed :)
